#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
strings:

对于单个字符的编码，Python提供了ord()函数获取字符的整数表示，chr()函数把编码转换为对应的字符
Python对bytes类型的数据用带b前缀的单引号或双引号表示
由于Python的字符串类型是str，在内存中以Unicode表示，一个字符对应若干个字节.
区分'ABC'和b'ABC'，前者是str，后者虽然内容显示得和前者一样，但bytes的每个字符都只占用一个字节

以Unicode表示的str通过encode()方法可以编码为指定的bytes
unicode 可以表示多个字节，utf-8变长字节，ascii一个字节

要把bytes变为str，就需要用decode()方法 
b'ABC',decode('ascii')

'''

len('string') //计算str包含多少个字符
len(b'abc') //计算字节数


