#!/usr/bin/env python3
# -*- coding: utf-8 -*-

class Chain(object):

    def __init__(self, path=''):
        self._path = path

    def __getattr__(self, path):
        return Chain('%s/%s' % (self._path, path))

    def __str__(self):
        return self._path

    __repr__ = __str__

'''
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

class Chain(object):
	def __init__(self,path=''):
		self._path=path
	def __getattr__(self,path):
		return Chain('%s/%s'%(self._path,path))
	def __str__(self):
		return self._path
	__repr__=__str__
	def users(self,name):
		self._name=name
		return Chain('%s/%s'%(self._path,self._name))
print(Chain().users('codd').repos)
'''
